//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualZoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Код_прав = 2;
        }
    
        public int Код { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> Код_прав { get; set; }
        public string ФИО { get; set; }
        public string email { get; set; }
        public bool Блокировка { get; set; }
    
        public virtual privilege privilege { get; set; }
    }
}
