//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualZoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class zoo
    {
        public int Number { get; set; }
        public string Name_of_the_animal { get; set; }
        public string Описание { get; set; }
        public string Interesting_fact { get; set; }
        public string Image { get; set; }
        public string sound { get; set; }
    }
}
